# Generated by Django 4.2.15 on 2024-08-29 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='username',
            field=models.CharField(max_length=32),
        ),
    ]
