# Generated by Django 4.2.15 on 2024-08-29 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_token_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='createTime',
            field=models.DateTimeField(default='2024-08-29 15:16:00'),
        ),
    ]
