# Generated by Django 4.2.15 on 2024-08-29 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_token_createtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='createTime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
