# Generated by Django 4.2.15 on 2024-09-12 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_token_createtime'),
    ]

    operations = [
        migrations.CreateModel(
            name='Components',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('initMethod', models.CharField(blank=True, max_length=500, null=True)),
                ('validateMethod', models.CharField(blank=True, max_length=500, null=True)),
                ('createTime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
